### ISSUE TITLE
Don't have access

### ISSUE THREAD

**Issue by ChrisJensenDK** [BSData/hobbit#1]
Whenever I try to commit, I'm notified I do not have permission to commit.
Any idea why this could be?

![skaermbillede 2015-02-25 kl 22 58 28](https://cloud.githubusercontent.com/assets/6816425/6381586/8ae9285a-bd42-11e4-8c9a-7b9bb188b0ec.png)

**Comment by amis92** [comment]
I forgot to add hobbit to the team you belong to (Data Authors - Other). Now it's all right. Sorry. :D

**Comment by ChrisJensenDK** [comment]
No worries, happy to see that it's fixed :D
