### ISSUE TITLE
Repo link not working and Isengard data error

### ISSUE THREAD

**Issue by paulsnoops** [BSData/hobbit#17]
The repo won't update to the latest version; saying this for weeks now. Other repos work fine.

> Details:
> Failed to download from one or more repositories
> 1) Failed to download data from http://battlescribedata.appspot.com/repos/hobbit/index.bsi. The repository is likely overloaded right now. Please try again later.
> 	at net.battlescribe.desktop.a.b$5.a(BattleScribe:362)
> 	at net.battlescribe.desktop.a.b$5.doInBackground(BattleScribe:341)
> 	at javax.swing.SwingWorker$1.call(Unknown Source)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at javax.swing.SwingWorker.run(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
> 	at java.lang.Thread.run(Unknown Source)

Also, Isengard says it is corrupted and BS deletes it. Tried re-downloading but same issue.

**Comment by amis92** [comment]
Fixed Isengard file corruption.
