### ISSUE TITLE
File Format Problem

### ISSUE THREAD

**Issue by Jonskichov** [BSData/hobbit#18]
@edhorsman 

I'm not sure why but it appears one or more of the Hobbit files is broken, preventing the data being available on the site.

Have you used some external tool to modify any files? The problem is the one described here: https://stackoverflow.com/questions/4569123/content-is-not-allowed-in-prolog-saxparserexception

Basically some extra character/data has found it's way into the start of one or more files, which causes the data site to throw an error.

I've seen this issue before, but I'm sure it's fixed on my end. Can you make sure you have the latest version of BattleScribe and go through each of the files, opening and re-saving each one. Hopefully this should resolve things.

**Comment by edhorsman** [comment]
@Jonskichov 

Thank you for the issue. I've done as you suggested, opening and re-saving each file, but I don't think has worked. As my knowledge of code amounts to about the same as a dinosaur, I've been using the Battlescribe Data Editor software; I do have the latest version of Battlescribe, and I have been using only this to edit/create files. 

I tried to use the Battlescribe Data Indexer once, but I didn't really understand what I was doing, and I think that's how I managed to screw things up. 

I'm very happy to try an resolve this issue, but as I don't really know what I'm doing with regards to this, any help would be really appreciated.

**Comment by Jonskichov** [comment]
No problem. I don't think the data editor is the problem, since you don't need to be using it for this site.

I'm guessing this is a bug somewhere down the line.

Just to be clear, the latest version right now is 2.00.16.

Can you tell me what platform you're using? Mac/Windows/Linux? I'll see if I can see what's going on.

**Comment by edhorsman** [comment]
Yup. That's the latest of Battlescribe I'm using. The platform I'm using is Windows 10

**Comment by Jonskichov** [comment]
Oops i meant that the Data Indexer shouldn't be the problem!
