### ISSUE TITLE
Hobbit SBG availability

### ISSUE THREAD

**Issue by ChrisJensenDK** [BSData/hobbit#2]
Just wondering how I make the Hobbit files I'm creating available on
http://battlescribedata.appspot.com/#/repos

Thanks!

**Comment by amis92** [comment]
Please read through https://github.com/BSData/bsdata/wiki/Developer-Guide - especially pay attention to **Releasing** paragraph. :)

**Comment by OftKilted** [comment]
Initial Release created for v0.1-beta
Lists open in v1.15 of battle scribe.
