### ISSUE TITLE
No 'evil armies'

### ISSUE THREAD

**Issue by hirwain** [BSData/hobbit#22]
Is there a reason why there's no entries for evil armies? ~~@amis~~ @amis92 (fixed the mention :) ~amis92)

**Comment by amis92** [comment]
I've put back Isengard file as it was commited originally (and fixed data file format errors) but I cannot vouch it'll be good, might be missing some stats or points, I don't play Hobbit so cannot check anything. Pushed release so it should be available within several hours. Please check back tomorrow and reopen if problem persists.
