### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by MJHastings** [BSData/hobbit#25]
Hello,

I would like access to edit this repository so that I can add missing races to the army lists - Moria, Mordor and others

Regards,

Matthew Hastings

**Comment by amis92** [comment]
Hello, @M-J-Hastings. Please accept the invitation in the email or on the [repo page](https://github.com/BSData/hobbit/invitations). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
