### ISSUE TITLE
Data Editing

### ISSUE THREAD

**Issue by MJHastings** [BSData/hobbit#26]
Hello,

I tried to sort Issue #23. I cloned the git. using GitHub app and made changes in the Data Editor app. I then created a new release with the altered file, Isengard.cat. However, when I refresh the repository data in the GitHub and Roster Editor apps the changes are not present.

Where am I going wrong? 

Thanks, M Hastings.

Post script: you may be able to see may trail of failure scattered across the Hobbit data page; if I've messed anything up go ahead and remove the changes/updates et cetera.

**Comment by amis92** [comment]
You may have to wait up to 12hrs, that's the interval at which refreshes are made.

**Comment by MJHastings** [comment]
AHA! Thanks for letting me know, it has now appeared.
