### ISSUE TITLE
Backups folder

### ISSUE THREAD

**Issue by amis92** [BSData/hobbit#35]
Hi,

@M-J-Hastings I think you're currently maintaining it. The repo should only contain .cat and .gst files (and readme); /backups folder is not supposed to be commited! Please remove it. It may cause issues in future.

**Comment by MJHastings** [comment]
@amis92 Okay, I had wondered. That was what was contained in the repository when I first started editing. Is there a method for keeping the backups public or is it reliant of private backups?

**Comment by amis92** [comment]
The GitHub itself is a backup system. You may want to befriend the "git" a little more ;) It's an Version Control System, and that's why you need to make commits. They mark points in history that you may want to revisit in case something goes wrong :) Cheers!

**Comment by MJHastings** [comment]
Perfect, I've removed it now and everything is ok.
