### ISSUE TITLE
Rename files so the data site can handle them.

### ISSUE THREAD

**Issue by Jonskichov** [BSData/hobbit#37]
Lothlórien_and_Mirkwood.cat and Númenor.cat need the accent characters taken out of the file name. The data site is having trouble with them and so users are not receiving these files.

**Comment by MJHastings** [comment]
I will fix this in the next release.
(I'm on holiday with limited Internet access until the new year so will get it out on the 3rd!)

**Comment by MJHastings** [comment]
Accented letter in file name was causing problems. Has been removed so should now be fixed.

**Comment by Jonskichov** [comment]
Looks good, nice one. I would have done it myself but didn't want to clash with anything you might be doing :)
