### ISSUE TITLE
[Anon] Bug report: Númenor.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/hobbit#5]
**File:** Númenor.catz

**BattleScribe version:** 1.15.07

**Platform:** Windows

**Dropbox:** No

**Description:** Hi,
When I try to download the hobbit data files I get the following error:
Details:
Errors occurred updating data files from repositories

> http://battlescribedata.appspot.com/repos/hobbit/index.bsi: Error updating from repository http://battlescribedata.appspot.com/repos/hobbit/index.bsi: BattleScribe failed to download and import one or more data files from the repository.
> net.battlescribe.model.dataindex.DataIndexEntry@1d0253b: http://battlescribedata.appspot.com/repos/hobbit/Númenor.catz
>     at net.battlescribe.desktop.b.j$1.a(BattleScribe:63)
>     at net.battlescribe.desktop.b.j$1.doInBackground(BattleScribe:40)
>     at javax.swing.SwingWorker$1.call(Unknown Source)
>     at java.util.concurrent.FutureTask.run(Unknown Source)
>     at javax.swing.SwingWorker.run(Unknown Source)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>     at java.lang.Thread.run(Unknown Source)

This seems to stop battlescribe from fetching all the files

**Comment by MJHastings** [comment]
Accented letter in file name was causing problems. Has been removed so should now be fixed.
