### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by edhorsman** [BSData/hobbit#6]
Hi,

I would like to join this repository to update it and try maintaining.

Best,
edhorsman

**Comment by amis92** [comment]
Hello, @edhorsman. Please accept the invitation in the email or on the [BSData organization webpage](https://github.com/BSData). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Also you can chim in in wh40k Gitter chat room (quite busy), if you have generic catalogue questions etc (GitHub login): [![Join the chat at https://gitter.im/BSData/wh40k](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/BSData/wh40k?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

Cheers!
